"""m2m2

Revision ID: 8a738ce822c2
Revises: e989139d4c8d
Create Date: 2024-02-12 10:11:19.266203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a738ce822c2'
down_revision: Union[str, None] = 'e989139d4c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_skill',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    op.drop_table('employee_skill')
    # ### end Alembic commands ###
